### ISSUE TITLE
Rapid create/destroy between step() causes SEGFAULT

### ISSUE THREAD

**Issue by ninnghazad** [louis-langholtz/PlayRho#306]
I know the reasons for doing this are questionable, but in rare circumstances it happens in my project.
I noticed this when spamming little grenades, which would spawn short-lived explosions. Sometimes a few factors would result in these explosions to be destroyed within the same frame they were created.
Creation and destruction both between calls to step(). Segfault will happen upon next step().
While being a weird usage-case, i still think this should work and not segfault. 
(Or assert if this isn't supposed to work.)
To isolate the issue i made the following minimal example:

```
//g++ -O3 -march=native -fsanitize=address -Isubmodules/PlayRho ideas_and_tests/cpp_playrho_rapid_create_and_destroy.cpp -o /tmp/test libs/libPlayRho.a 

#include <PlayRho/PlayRho.hpp>
#include <iostream>
#include <iomanip>
#include <cstdlib>

using namespace playrho;
using namespace playrho::d2;

double rnd() {
	return (double)std::rand()/RAND_MAX;
}
int main()
{
	auto world = World{};

	const auto ground = world.CreateBody(BodyConf{}.UseLocation(Length2{0_m, -10_m}));
	const auto box = Shape{PolygonShapeConf{}.SetAsBox(50_m, 10_m)};
	ground->CreateFixture(box);

	const auto stepConf = StepConf{};
	std::cout << std::fixed << std::setprecision(2);
	
	std::vector<decltype(world.CreateBody())> bodies;
	for (auto i = 0; i < 60; ++i) {
		std::cout << "Step begin" << std::endl;
		world.Step(stepConf);
		std::cout << "Step finish" << std::endl;
		
		for (auto j = 0; j < 60; ++j) {
			if(rnd() > 0.5) {
				auto body = world.CreateBody(BodyConf{}
						.UseLocation(Length2{0_m, 4_m})
						.UseType(BodyType::Dynamic)
						.UseLinearAcceleration(EarthlyGravity));

				body->CreateFixture(Shape{DiskShapeConf{}.UseRadius(1_m)});
				
				bodies.push_back(body);
				std::cout << "Create body #" << bodies.size() << std::endl;
			}
			if(rnd() > 0.5 && !bodies.empty()) {
				world.Destroy(*bodies.begin());
				bodies.erase(bodies.begin());
				std::cout << "Destroy body #" << 0 << std::endl;
			}
		}
	}

	return 0;
}
```

result:

```
$ g++ -O3 -march=native -fsanitize=address -Isubmodules/PlayRho ideas_and_tests/cpp_playrho_rapid_create_and_destroy.cpp -o /tmp/test libs/libPlayRho.a 
$ /tmp/test

Step begin
Step finish
Create body #1
Create body #2
Destroy body #0
Create body #2
Destroy body #0
Destroy body #0
Create body #1
Destroy body #0
Create body #1
Destroy body #0
Create body #1
Create body #2
Destroy body #0
Create body #2
Create body #3
Destroy body #0
Destroy body #0
Destroy body #0
Create body #1
Destroy body #0
Create body #1
Destroy body #0
Create body #1
Destroy body #0
Create body #1
Destroy body #0
Create body #1
Destroy body #0
Create body #1
Destroy body #0
Create body #1
Destroy body #0
Create body #1
Destroy body #0
Create body #1
Create body #2
Destroy body #0
Create body #2
Destroy body #0
Destroy body #0
Create body #1
Destroy body #0
Create body #1
Destroy body #0
Create body #1
Destroy body #0
Create body #1
Destroy body #0
Create body #1
Create body #2
Create body #3
Create body #4
Destroy body #0
Step begin
ASAN:DEADLYSIGNAL
=================================================================
==24075==ERROR: AddressSanitizer: SEGV on unknown address 0x61205b000081 (pc 0x563f096a19b2 bp 0x7ffc9022dc80 sp 0x7ffc9022cbc0 T0)
==24075==The signal is caused by a READ memory access.
    #0 0x563f096a19b1 in playrho::d2::Fixture::GetBody() const [...]/submodules/PlayRho/PlayRho/../PlayRho/Dynamics/Fixture.hpp:229
    #1 0x563f096a19b1 in playrho::d2::World::CreateAndDestroyProxies(playrho::d2::Fixture&, playrho::StepConf const&) [...]/submodules/PlayRho/PlayRho/Dynamics/World.cpp:2275
    #2 0x563f096a1a74 in operator() [...]/submodules/PlayRho/PlayRho/Dynamics/World.cpp:2268
    #3 0x563f096a1a74 in for_each<__gnu_cxx::__normal_iterator<playrho::d2::Fixture**, std::vector<playrho::d2::Fixture*> >, playrho::d2::World::CreateAndDestroyProxies(const playrho::StepConf&)::<lambda(playrho::d2::Fixture*)> > /usr/include/c++/6/bits/stl_algo.h:3769
    #4 0x563f096a1aa2 in playrho::d2::World::CreateAndDestroyProxies(playrho::StepConf const&) [...]/submodules/PlayRho/PlayRho/Dynamics/World.cpp:2269
    #5 0x563f096a73f4 in playrho::d2::World::Step(playrho::StepConf const&) [...]/submodules/PlayRho/PlayRho/Dynamics/World.cpp:1818
    #6 0x563f0968e821 in main (/tmp/test+0x6821)
    #7 0x7f6fd703af29 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20f29)
    #8 0x563f09690a09 in _start (/tmp/test+0x8a09)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV [...]/submodules/PlayRho/PlayRho/../PlayRho/Dynamics/Fixture.hpp:229 in playrho::d2::Fixture::GetBody() const
==24075==ABORTING

```

**Comment by ninnghazad** [comment]
This seems to fix it for me - in how far that is an actual solution i don't know.
```
diff --git a/PlayRho/Dynamics/World.cpp b/PlayRho/Dynamics/World.cpp
index 4ac6f78f..2f6bf1f9 100644
--- a/PlayRho/Dynamics/World.cpp
+++ b/PlayRho/Dynamics/World.cpp
@@ -785,6 +785,12 @@ void World::Destroy(Body* body)
         {
             m_destructionListener->SayGoodbye(fixture);
         }
+       if(!m_fixturesForProxies.empty()) {
+               m_fixturesForProxies.erase(
+                       std::remove(m_fixturesForProxies.begin(), m_fixturesForProxies.end(), &fixture),
+                       m_fixturesForProxies.end()
+               );
+       }
         DestroyProxies(fixture);
         FixtureAtty::Delete(&fixture);
     });
```

**Comment by louis-langholtz** [comment]
Sorry about this bug. I'm very impressed by your write-up though!

**Comment by louis-langholtz** [comment]
Fixed this bug and related others.
